# Análisis numérico matricial
Los métodos implementados son los siguientes:
- Factorización LU: `factorizacion_lu`.
- Factorización de Cholesky: `factorizacion_cholesky`.

In [1]:
from numpy import *

## Factorización LU
Dada $A \in \mathcal{M}_n(\mathbb{C})$ inversible, se llama factorización LU a la descomposición, si es posible,
$$A = LU,$$
siendo $L \in \mathcal{M}_n(\mathbb{C})$ triangular inferior, inversible y con unos en la diagonal principal, y $U \in \mathcal{M}_n(\mathbb{C})$ triangular superior e inversible.

Si todas las submatrices principales de $A$ son también inversibles, entonces la factorización LU existe y es única.

In [2]:
def factorizacion_lu(A):
    tolerancia = 1e-15
    m, n = shape(A)
    if m != n:
        print("La matriz no es cuadrada.")
        return None
    
    if A.dtype == complex:
        L = eye(n, dtype =  complex)
        U = array(A, dtype = complex)
    else:
        L = eye(n, dtype =  float)
        U = array(A, dtype = float)

    for k in range(n-1):
        if abs(A[k, k]) < tolerancia:
            print("No existe la factorización LU.")
            return None
        else:
            for i in range(k+1, n):
                L[i, k] = U[i, k]/U[k, k]
                U[i, k:] -= U[k, k:]*L[i, k]

    return L, U

Realizamos la factorización LU de la matriz
$$A = \begin{pmatrix}
2 & -1 & 4 & 0 \\
4 & -1 & 5 & 1 \\
-2 & 2 & -2 & 3 \\
0 & 3 & -9 & 4
\end{pmatrix}.$$

In [3]:
A = array([
    [2, -1, 4, 0],
    [4, -1, 5, 1],
    [-2, 2, -2, 3],
    [0, 3, -9, 4]
])
print("Matriz A\n", A)

L, U = factorizacion_lu(A)
print("Matriz L\n", L)
print("Matriz U\n", U)

Matriz A
 [[ 2 -1  4  0]
 [ 4 -1  5  1]
 [-2  2 -2  3]
 [ 0  3 -9  4]]
Matriz L
 [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [-1.  1.  1.  0.]
 [ 0.  3.  0.  1.]]
Matriz U
 [[ 2. -1.  4.  0.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  5.  2.]
 [ 0.  0.  0.  1.]]


## Factorización de Cholesky
Dada $A \in \mathcal{M}_n(\mathbb{C})$ hermítica e inversible, se llama factorización de Cholesky a la descomposición, si es posible,
$$A = CC^\ast,$$
siendo $C \in \mathcal{M}_n(\mathbb{C})$ triangular inferior e inversible.

Si $A$ es definida positiva, entonces la factorización de Cholesky existe.
Además, si se impone que todos los elementos diagonales de la matriz $C$ sean positivos, entonces la factorización es única.

In [4]:
def factorizacion_cholesky(A):
    tolerancia = 1e-15
    m, n = shape(A)
    if m != n:
        print("La matriz no es cuadrada.")
        return None

    if A.dtype == complex:
        C = zeros((n, n), complex)
    else:
        C = zeros((n, n), float)

    for i in range(n):
        C[i, i] = sqrt(A[i, i] - sum(abs(C[i, :i])**2))
        if abs(C[i, i]) < tolerancia:
            print("No existe la factorización de Cholesky.")
            return None
        else:
            for j in range(i+1, n):
                C[j, i] = (A[i, j] - sum(C[i, :i]*C[j, :i]))/C[i, i]
    
    return C

Realizamos la factorización de Cholesky de la matriz
$$ A = \begin{pmatrix}
1 & 2 & 3 & 4 \\
2 & 5 & 1 & 10 \\
3 & 1 & 35 & 5 \\
4 & 10 & 5 & 45
\end{pmatrix}.$$

In [5]:
A = array([
    [1, 2, 3, 4],
    [2, 5, 1, 10],
    [3, 1, 35, 5],
    [4, 10, 5, 45]
])
print("Matriz A\n", A)

C = factorizacion_cholesky(A)
print("Matriz C\n", C)

Matriz A
 [[ 1  2  3  4]
 [ 2  5  1 10]
 [ 3  1 35  5]
 [ 4 10  5 45]]
Matriz C
 [[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3. -5.  1.  0.]
 [ 4.  2.  3.  4.]]
